### ISSUE TITLE
/bin/sh: 1: psftp: not found

### ISSUE THREAD

**Issue by BaseMax** [Luis97lol/psftp-action#1] opened 2022-09-07 17:30 UTC
```
on: [push]

jobs:
  upload_to_sftp:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: P-SFTP
        uses: Luis97lol/PSFTP@v1.3
        with:
          host: 'xxxxxxxx.com'
          user: 'xxxxxxxx'
          pass: ${{ secrets.FTP_PASSWORD }}
          scriptPath: deploy.sh
```

Action Logs:

```
Run Luis97lol/PSFTP@v[1](https://github.com/BaseMax/KareMan/runs/8233919805?check_suite_focus=true#step:3:1).3
error: Command failed: psftp "xxxxxxxx.com" -l "xxxxxxxx" -pw "***" -b deploy.sh
/bin/sh: 1: psftp: not found
```

**Comment by Luis97lol** [comment] 2022-09-07 18:52
Hi @BaseMax ! The action is correctly setted up on your .yml. The log error is due to the psftp executable not being installed correctly on the host machine. ¿Are you using GitHub Runners or Self-Hosted Runner?

**Comment by BaseMax** [comment] 2022-09-07 18:57
Thank you for your message. It's GitHub Action

**Comment by Luis97lol** [comment] 2022-09-07 21:02
I'm not tested it on GitHub Runner. @BaseMax You can try executing the installation command before running the action:
`apt-get install putty-tools`

**Comment by Luis97lol** [comment] 2022-09-09 11:06
Hi @BaseMax ! I have reproduced the issue in one of my projects. The .yml pipeline file to run on a GitHub machine must contain the following line of code before running my GitHub Action
```
steps:
    - run: sudo apt-get install putty-tools
    - uses: Luis97lol/PSFTP@v1.3
      with:
        host: ${{ secrets.SFTP_HOST }}
        user: ${{ secrets.SFTP_USER }}
        pass: ${{ secrets.SFTP_PASS }}
        scriptPath: deploy.sh
```

**Comment by BaseMax** [comment] 2022-09-09 11:43
Thanks for checking.

**Comment by Luis97lol** [comment] 2022-09-09 16:42
Hi there @BaseMax . I recommend you to upgrade PSFTP action to the new version 1.4 Accuracy. By using GitHub machines, it doesn't have cached your host ssh-key. On Self-Hosted machines it's only needed on the first connection but GitHub machines are requested on demand and probably are virtualized. So you need to indicate it always.  PSFTP v1.4 allows you pass an optional parameter as the hostkey. I'm going to proceed closing this issue. Please, re-open it if needed. Thanks for using the action :-).

**Closed as completed** 2022-09-09 16:43 UTC
Labels: good first issue
